name: CI Pipeline

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

jobs:
    test:
        runs-on: ubuntu-latest

        services:
            redis:
                image: redis:6
                ports:
                - 6379:6379

        steps:
        -   name: Checkout 
            uses: actions/checkout@v3
        -   name: Set Docker Buildx
            uses: docker/setup-buildx-action@v3

        -   name: Construir Docker image
            run: docker build -t my-event-engine .

        -   name: Correr tests dentro del contenedor
            run: |
                docker run --rm \
                --network host \
                -v ${{ github.workspace }}/tests:/app/tests \
                my-event-engine \
                pytest /app/tests --maxfail=1 --disable-warnings -v
