name: CI Pipeline

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

jobs:
    test:
        runs-on: ubuntu-latest

        services:
            redis:
                image: redis:6
                ports:
                - 6379:6379

        steps:
        -   name: Checkout 
            uses: actions/checkout@v3

        -   name: Python base
            uses: actions/setup-python@v4
            with:
                python-version: "3.10"

        -   name: Instalamos depenndencias
            run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
                pip install flake8 pytest

        -   name: Lint con flake8
            run: |
                flake8 tests
        -   name: Prepare folders
            run: |
                mkdir -p /app/data
                mkdir -p /app/reports
        -   name: corremos pytest
            run: |
                pytest --maxfail=1 --disable-warnings -v
